name: chatview_utility
description: Utility library for the chatview and chatview_db_connection libraries, containing shared type declarations. It should not be used directly.
version: 0.0.1
repository: https://github.com/SimformSolutionsPvtLtd/chatview_utility
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview_utility/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
