name: chatview_models
description: Utility library for the chatview and chatview_db_connection libraries which contains shared type declarations. Should not be used directly.
version: 0.0.1
repository: https://github.com/SimformSolutionsPvtLtd/chatview_models
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview_models/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
